version: "3.9"

services:
  web:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate 
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
      - redis
  redis:
    image: redis:6-alpine
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_django
  celery:
    build: .
    command: celery -A event_registration worker -l info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
  nginx:
    build: ../server

    ports:
      - "8000:80"
    depends_on:
      - web
    volumes:
      - ../server/services.conf:/etc/nginx/conf.d/default.conf
