# Generated by Django 4.2.5 on 2023-09-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(default="default_image.jpg", upload_to="events/"),
        ),
    ]
