# Generated by Django 4.2.5 on 2023-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(default="default_image.png", upload_to="events/"),
        ),
    ]
