# Generated by Django 4.2.5 on 2023-09-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(max_length=600),
        ),
    ]
