# Generated by Django 4.2.5 on 2023-09-07 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0010_participant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("conference", "Conference"),
                    ("seminar", "Seminar"),
                    ("workshop", "Workshop"),
                    ("webinar", "Webinar"),
                ],
                default="conference",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(default="default_event.png", upload_to="events/"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default_user.png",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
