# Generated by Django 4.2.5 on 2023-09-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_event_event_type_alter_event_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("conference", "Conference"),
                    ("seminar", "Seminar"),
                    ("workshop", "Workshop"),
                    ("webinar", "Webinar"),
                ],
                default="conference",
                max_length=30,
            ),
        ),
    ]
