# Generated by Django 4.2.5 on 2023-09-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
