# Generated by Django 4.2.5 on 2023-09-08 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_alter_eventregistration_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together=set(),
        ),
    ]
